services:
  dnsserver:
    build:
      context: ./servidor
      dockerfile: Dockerfile-servidorDNS
    image: ubuntu/bind9:tallerdns01-servidor
    container_name: dnsserver
    volumes:
      - ./servidor/etc/bind:/etc/bind
    networks:
      - tallerdns

  dnsclient:
    build:
      context: ./
      dockerfile: Dockerfile-clienteDNS
    image: ubuntu:tallerdns01-cliente
    container_name: dnsclient
    stdin_open: true
    networks:
      - tallerdns

networks:
  tallerdns:
